# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Check if we have the necessary plugin.
  unless Vagrant.has_plugin?("vagrant-reload")
    abort 'Plugin needed: vagrant-reload. Run the following command to install: vagrant plugin install vagrant-reload'
  end

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "modernIE/w7-ie11"

  # Set VM host name
  config.vm.hostname = "FSE-2012-SecuriTAS"

  config.vm.boot_timeout = 600

  config.vm.guest = :windows

  # Will use winrm instead of SSH since this is a Windows VM.
  config.vm.communicator = "winrm"

  # Set up synced folder.
  config.vm.synced_folder "files/", "C:/tool_files/"

  # Provider setup - 2GB RAM, and 64MB VRAM with 2 cores.
  config.vm.provider "virtualbox" do |vb|
        # Start in gui mode.
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--vram", "64"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        # Disable USB 2.0
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
        vb.name = "FSE-2012-SecuriTAS"   
    end
  
  # Port forward WinRM and RDP
  config.vm.network :forwarded_port, guest: 3389, host: 3377, id: "rdp", auto_correct: false
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.windows.set_work_network = true
  config.winrm.max_tries = 10

  # Get jdk 1.6
  config.vm.provision :shell, path: "shell/GetJava.bat"

  # Get Eclipse
  config.vm.provision :shell, path: "shell/GetEclipse.bat"  

  # Get JBoss
  config.vm.provision :shell, path: "shell/GetJBoss.bat"

  # Get SecuriTAS
  config.vm.provision :shell, path: "shell/GetSecuriTAS.bat"

  # Get MySql
  config.vm.provision :shell, path: "shell/GetMySql.bat"

  # Set environment variables.
  config.vm.provision :shell, path: "shell/SetEnvVar.bat"

  # Get patch files.
  config.vm.provision :shell, path: "shell/GetFiles.bat"

  # Get Graphviz
  config.vm.provision :shell, path: "shell/GetGraphviz.bat"

  # Reload machine, ready to test!
  config.vm.provision :reload

end
